POST http://localhost:8082/users
Content-Type: application/json

{
  "first_name": "Mirzoakhmedov",
  "last_name": "Schahrom",
  "login": "raznollik",
  "email": "schahrom1232939@gmail.com",
  "password": "some_password"
}
###
